import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Removed Poppins
import "./globals.css";

// Load Geist fonts
const geistSans = Geist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Ensure correct font weights
  variable: "--font-geist-sans", // Link to CSS variable
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono", // Link to CSS variable
});

export const metadata: Metadata = {
  title: "CPR/BLS Training",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
